final products = [
  {
    'id': '0',
    'title': 'Men\'s Tommmy Shirts',
    'price': 444.00,
    'imageUrl': 'assets/images/shirts_1.png',
    'company': 'Tommy Hilfiger',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '2',
    'title': 'Men Brown Pocket Print Oversize T-shirt',
    'price': 844.99,
    'imageUrl': 'assets/images/shirts_2.png',
    'company': 'Peter England',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '3',
    'title': 'men\'s tshirt',
    'price': 200.00,
    'imageUrl': 'assets/images/shirts_3.png',
    'company': 'Raymond',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '4',
    'title': 'Floral Printed Extended Sleeves Loose T-shirt',
    'price': 445.99,
    'imageUrl': 'assets/images/shirts_4.png',
    'company': 'Louis Philippe',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '5',
    'title': 'men\'sVan Heusen Shirts',
    'price': 949.00,
    'imageUrl': 'assets/images/shirts_5.png',
    'company': 'sVan Heusen',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '6',
    'title': 'Graphic Printed Oversized Fit Cotton T-shirt',
    'price': 744.33,
    'imageUrl': 'assets/images/shirts_6.png',
    'company': 'Blackberrys',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '7',
    'title': 'men\'s Creams Shirts',
    'price': 4440.33,
    'imageUrl': 'assets/images/shirts_7.png',
    'company': 'J.Crew',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '8',
    'title': 'Mens Brown Printed Oversized T-shirt',
    'price': 909.99,
    'imageUrl': 'assets/images/shirts_8.png',
    'company': 'Allen Solly',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '9',
    'title': 'Mens Brown Printed Oversized T-shirt',
    'price': 199.00,
    'imageUrl': 'assets/images/shirts_9.png',
    'company': 'Allen Solly',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '10',
    'title': 'Girls Floral Print Puff Sleeves Fit & Flare Dress',
    'price': 999.00,
    'imageUrl': 'assets/images/shirts_10.png',
    'company': 'Includ',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '11',
    'title': 'Mens Brown Printed Oversized T-shirt',
    'price': 220.00,
    'imageUrl': 'assets/images/shirts_11.png',
    'company': 'Allen Solly',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '12',
    'title': 'Cream Shimmer Maxi Dress',
    'price': 1299.99,
    'imageUrl': 'assets/images/shirts_12.png',
    'company': 'Allen Solly',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '13',
    'title': 'Mesh Ruffle Green Maxi Dress',
    'price': 259.00,
    'imageUrl': 'assets/images/shirts_13.png',
    'company': 'Littlebox India',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '14',
    'title': 'Miss & Chief Girls Midi/Knee Length Party Dress',
    'price': 1899.99,
    'imageUrl': 'assets/images/shirts_14.png',
    'company': 'Littlebox India',
    'sizes': [28, 30, 32, 34, 36],
  },
  {
    'id': '15',
    'title': 'BAESD Floral Print Applique Crepe A-Line Dress (9-10Y) by Myntra',
    'price': 2000.99,
    'imageUrl': 'assets/images/shirts_15.png',
    'company': 'New Basicsy',
    'sizes': [28, 30, 32, 34, 36],
  },
];
